[prune]
  go-tests = true
  unused-packages = true

#[[constraint]]
#  name = "go.mongodb.org/mongo-driver"
#  version = "1.3.0"

#[[constraint]]
#  branch = "master"
#  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.3.0"